services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
      - API_ENDPOINT=${API_ENDPOINT}
      - API_MODEL=${API_MODEL}
      - RATE_LIMIT_WINDOW_MS=86400000
      - RATE_LIMIT_MAX_REQUESTS=5
    restart: unless-stopped 